#pragma once
#ifndef LANG_H
#define LANG_H

#define WELCOME "欢迎来到2048游戏！\n版本号：V1.0\nFishy设计\n\n"
#define MODE_SELECT "请选择功能：\n"
#define MODES "继续(C)，新游戏(N)，排行榜(L)，退出(Q)\n"
#define EXIT_GAME "退出游戏！\n"
#define LEADERBOARD_TITLE "排行榜\n\n"
#define LEADERBOARD_INS "\n返回(B)，重置排行榜分数(R)\n"
#define LEADERBOARD_CLEAR "排行榜分数已重置！\n"
#define CONFIRM_NEWGAME "检测到未完成的游戏，继续玩(C)，还是开始新游戏(N)\n开始新游戏会导致存档丢失哦~\n"
#define FINISHED_GAME "没有检测到存档，请开始新游戏！\n"
#define CONTINUE_LASTGAME "加载存档\n"
#define START_NEWGAME "开始新游戏\n"
#define DURING_GAME_TITLE "2048\n\n"
#define GAME_INSTRUCTION "使用方向键来操作数字\n"
#define GAME_OPERATION "按Q退出游戏，按S保存当前游戏\n\n"
#define CURRENT_SCORE "当前分数："
#define HIGHEST_SCORE "最高分数："
#define COMBOS "Combos!"
#define SAVE_GAME_HINT "游戏还没结束呢，需要保存吗？(Y/N)\n"
#define GAME_SAVED "游戏已保存！"
#define INPUT_TEXT "请按方向键"
#define HINT "提示"
#define LOSE_TITLE "您输了！"
#define WIN_TITLE "您赢了！"
#define NEW_HIGHSCORE "您创造了新纪录！"
#define GOTON_LEADERBOARD "您上排行榜了！"
#define NEW_TILE_BONUS "新数字出现，获得奖励！"
#define GAME_UNSAVED "游戏未保存！"
#define END_OF_GAME "返回首页或退出？ (Y -> 首页 / N -> 退出)\n"
#define BONUS_500 "奖励500分"
#define BONUS_1000 "奖励1000分"
#define BONUS_5000 "奖励5000分"
#define ERROR_0 "Error!"
#define ERROR_1 "File lb.sav is missing. Game initializing failed. | code(-1)"
#define ERROR_2 "File sg.sav is missing. Game initializing failed. | code(-2)"
#define ERROR_3 "File lb.sav corrupted. Please reinstall the game. | code(-3)"
#define ERROR_4 "File sg.sav corrupted. Please reinstall the game. | code(-4)"

#endif
